[package]
name = "vm"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
arbitrary = { version = "1.3.2", features = ["derive"] }
rand = "0.8.5"
standard-dist = "1.0.0"
